"""
Samtec Brochure Generator — Streamlit UI
FSE fills in customer context and gets 2-3 brochure variants side by side.
Runs against a pre-built knowledge JSON (Stage 2 output).
"""

import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

import streamlit as st

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------
st.set_page_config(
    page_title="Samtec Brochure Generator",
    page_icon="📡",
    layout="wide",
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

KNOWLEDGE_FILES = sorted(Path(".").glob("*_knowledge.json"))
KNOWLEDGE_OPTIONS = {f.stem.replace("_knowledge", "").replace("_", " ").title(): str(f)
                     for f in KNOWLEDGE_FILES}

PRESET_ANGLES = [
    "Emphasize high-frequency performance and mode-free operation",
    "Emphasize blind-mate density and board space savings",
    "Emphasize shock & vibration mechanical robustness",
    "Emphasize adaptor ecosystem and compatibility",
    "Emphasize 5G / radar / defense application fit",
    "(Custom — type below)",
]

PRESET_CONTEXTS = [
    "RF-heavy design-in, shock and vibration environment",
    "High-density board layout, space-constrained chassis",
    "mmWave / 5G infrastructure, high frequency above 40 GHz",
    "Military / defense / radar, ruggedized field deployment",
    "Test & measurement, lab environment, precision interconnect",
    "(Custom — describe below)",
]


def run_stage3(knowledge_path: str, customer: str, contact: str,
               context: str, angle: str) -> str:
    """Call stage3_generate.py and return the markdown output as a string."""
    with tempfile.NamedTemporaryFile(suffix=".md", delete=False, mode="w") as tmp:
        out_path = tmp.name

    result = subprocess.run(
        [
            sys.executable, "stage3_generate.py",
            "--knowledge", knowledge_path,
            "--customer", customer,
            "--contact", contact or "—",
            "--context", context,
            "--angle", angle,
            "--output", out_path,
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        return f"**Error running generator:**\n\n```\n{result.stderr}\n```"

    return Path(out_path).read_text(encoding="utf-8")


def count_needs_input(md: str) -> int:
    return len(re.findall(r"^- \[ \]", md, re.MULTILINE))


def count_cited_claims(md: str) -> int:
    return len(re.findall(r"\*\[.+?\]\*", md))


def compliance_passed(md: str) -> bool:
    return "✅" in md and "UNCITED ITEMS" not in md


# ---------------------------------------------------------------------------
# Sidebar — knowledge file selector
# ---------------------------------------------------------------------------
with st.sidebar:
    st.image("https://www.samtec.com/images/default-source/logo/samtec-logo.png",
             width=160, use_column_width=False)
    st.markdown("## Brochure Generator")
    st.caption("Field Sales Engineer Tool — Internal Use Only")
    st.divider()

    if not KNOWLEDGE_OPTIONS:
        st.error("No knowledge files found. Run Stage 1 + 2 first.")
        st.stop()

    selected_family = st.selectbox(
        "Product Family",
        options=list(KNOWLEDGE_OPTIONS.keys()),
        help="Knowledge files are generated by running stage1_ingest.py + stage2_structure.py",
    )
    knowledge_path = KNOWLEDGE_OPTIONS[selected_family]

    with open(knowledge_path) as f:
        knowledge = json.load(f)

    gap_count = len(knowledge.get("gaps", []))
    spec_count = sum(len(v) for v in knowledge["key_specs"].values())
    st.caption(f"Sources: {', '.join(knowledge.get('source_files', []))}")
    st.caption(f"Spec items: {spec_count} | Known gaps: {gap_count}")
    st.divider()
    st.caption("v1.0 — All claims sourced from Samtec materials only.")

# ---------------------------------------------------------------------------
# Main — Customer context form
# ---------------------------------------------------------------------------
st.title(f"📡 {selected_family} — Customer Brochure Generator")
st.caption("Fill in customer context below. The tool generates 2–3 brochure variants "
           "using only verified Samtec source material. No claims are invented.")

st.divider()

col_left, col_right = st.columns([1, 1])

with col_left:
    st.subheader("Customer Info")
    customer = st.text_input("Customer / Account Name", placeholder="e.g. GTRI, Raytheon, Keysight")
    contact = st.text_input("Point of Contact", placeholder="e.g. Dr. Jane Smith (optional)")

    st.subheader("Application Context")
    context_preset = st.selectbox("Application environment", PRESET_CONTEXTS)
    if context_preset == "(Custom — describe below)":
        context = st.text_area("Describe the application context",
                               placeholder="e.g. airborne radar system, shock-rated chassis, needs 40+ GHz",
                               height=80)
    else:
        context_extra = st.text_input("Any additional detail to add?",
                                      placeholder="optional — e.g. also buying RF adaptors")
        context = context_preset + (f", {context_extra}" if context_extra.strip() else "")

with col_right:
    st.subheader("FSE Angles (choose up to 3)")
    st.caption("Each checked angle generates one brochure variant.")

    selected_angles = []
    custom_angle_text = ""

    for angle in PRESET_ANGLES[:-1]:
        if st.checkbox(angle, key=f"angle_{angle}"):
            selected_angles.append(angle)

    use_custom = st.checkbox("Custom angle")
    if use_custom:
        custom_angle_text = st.text_input("Describe your angle",
                                          placeholder="e.g. Emphasize cross-sell with Bulls Eye, contact is a bull")
        if custom_angle_text.strip():
            selected_angles.append(custom_angle_text.strip())

    if len(selected_angles) > 3:
        st.warning("More than 3 angles selected — only the first 3 will be generated.")
        selected_angles = selected_angles[:3]

    st.subheader("Cross-Sell / Relationship Notes")
    cross_sell = st.text_area(
        "Any relationship context to surface?",
        placeholder="e.g. Team member loves Bulls Eye. Account also buys lots of RF adaptors.",
        height=80,
    )

st.divider()

generate_btn = st.button("🚀 Generate Brochure Variants", type="primary",
                          disabled=not (customer.strip() and context.strip() and selected_angles))

if not customer.strip():
    st.caption("Enter a customer name to enable generation.")
if not selected_angles:
    st.caption("Select at least one FSE angle to enable generation.")

# ---------------------------------------------------------------------------
# Generation
# ---------------------------------------------------------------------------
if generate_btn:
    if not customer.strip() or not context.strip() or not selected_angles:
        st.error("Please fill in customer name, context, and at least one angle.")
        st.stop()

    # Append cross-sell note to the context if provided
    full_context = context
    if cross_sell.strip():
        full_context += f". Cross-sell context: {cross_sell.strip()}"

    tabs = st.tabs([f"Variant {i+1}: {a[:45]}…" if len(a) > 45 else f"Variant {i+1}: {a}"
                    for i, a in enumerate(selected_angles)])

    for i, (tab, angle) in enumerate(zip(tabs, selected_angles)):
        with tab:
            with st.spinner(f"Generating variant {i+1}…"):
                md = run_stage3(
                    knowledge_path=knowledge_path,
                    customer=customer.strip(),
                    contact=contact.strip(),
                    context=full_context,
                    angle=angle,
                )

            # Status bar
            needs = count_needs_input(md)
            cited = count_cited_claims(md)
            passed = compliance_passed(md)

            m1, m2, m3 = st.columns(3)
            m1.metric("Cited claims", cited)
            m2.metric("NEEDS INPUT items", needs, delta=f"{'resolve before sending' if needs else 'none'}")
            m3.metric("Compliance", "✅ Pass" if passed else "⚠️ Review")

            st.divider()

            # Split brochure body from compliance section for display
            compliance_split = md.split("## Compliance Check")
            brochure_body = compliance_split[0]
            compliance_section = "## Compliance Check" + compliance_split[1] if len(compliance_split) > 1 else ""

            st.markdown(brochure_body)

            with st.expander("🔍 Compliance Check & Source Trace"):
                st.markdown(compliance_section)

            st.divider()
            st.download_button(
                label=f"⬇️ Download Variant {i+1} (.md)",
                data=md,
                file_name=f"{re.sub(r'[^a-z0-9]', '_', customer.lower())}_{selected_family.lower().replace(' ', '_')}_variant{i+1}.md",
                mime="text/markdown",
                key=f"download_{i}",
            )
